<a href="https://colab.research.google.com/github/Ukejee/HamoyeIntern/blob/master/Data_ScienceQuiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

#pd.set_option('display.width', 400)
#pd.set_option('display.max_columns', 15)
fuel_data = pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")

#Question One
A = [1,2,3,4,5,6]
B = [13, 21, 34]

a = pd.Series(A)
b = pd.Series(B)
A_B = a.append(b)
print(A_B)

#Question Two
print(np.identity((3)))

#Question Three
print(fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].describe())

#Question Four
print(fuel_data.describe().to_string())

#Question Five
print(fuel_data["fuel_qty_burned"].skew())
print(fuel_data["fuel_qty_burned"].kurtosis())

#Question Six
print(fuel_data.isnull().sum())
print(fuel_data["fuel_unit"].count())
print(fuel_data.isnull().sum()/fuel_data["fuel_unit"].count() * 100)

#Question Eight
print(fuel_data.corr(method="pearson").to_string)

#Question Nine
print(fuel_data.groupby("report_year")["fuel_cost_per_unit_burned"].describe())

#Question Ten
print(fuel_data.groupby("report_year")["fuel_cost_per_unit_delivered"].describe())


0     1
1     2
2     3
3     4
4     5
5     6
0    13
1    21
2    34
dtype: int64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
                       count         mean  ...       75%         max
fuel_type_code_pudl                        ...                      
coal                  8547.0    67.421830  ...  44.66800   44033.320
gas                  11486.0    13.659397  ...   6.96000   10490.000
nuclear                818.0  4955.157002  ...  50.85525   69785.215
oil                   8064.0   168.877086  ...  98.68925  139358.000
other                  167.0    18.253856  ...  20.05500     134.547
waste                  441.0    19.518122  ...  32.65000     132.291

[6 rows x 8 columns]
       utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu
count      29523.000000  29523.000000     2.952300e+04         29523.000000               29523.000000                  2.952300e+04         29523.000